<?php

use App\Commands\TriageListenCommand;
use Illuminate\Support\Facades\Http;
use Prism\Prism\Enums\FinishReason;
use Prism\Prism\Facades\Prism;
use Prism\Prism\Text\Response as TextResponse;
use Prism\Prism\ValueObjects\Meta;
use Prism\Prism\ValueObjects\Usage;

function makeEvent(array $overrides = []): string
{
    return json_encode(array_replace_recursive([
        'eventType' => 'issues',
        'payload' => [
            'action' => 'opened',
            'repository' => ['full_name' => 'jordanpartridge/triage-agent'],
            'issue' => [
                'number' => 42,
                'title' => 'Add dark mode',
                'body' => 'We need a dark mode toggle in the settings page.',
            ],
        ],
    ], $overrides));
}

function fakePrism(string $text = '## Plan\nImplement dark mode.'): void
{
    Prism::fake([
        new TextResponse(
            steps: collect([]),
            text: $text,
            finishReason: FinishReason::Stop,
            toolCalls: [],
            toolResults: [],
            usage: new Usage(10, 20),
            meta: new Meta('ollama', 'deepseek-coder:6.7b'),
            messages: collect([]),
            additionalContent: [],
        ),
    ]);
}

it('triages a new issue and posts a comment', function () {
    fakePrism('## Plan\nImplement dark mode.');

    Http::fake([
        'api.github.com/*' => Http::response([], 201),
    ]);

    $command = app(TriageListenCommand::class);

    // Simulate the Redis callback directly
    $reflection = new ReflectionMethod($command, 'shouldProcess');
    $event = json_decode(makeEvent(), true);
    expect($reflection->invoke($command, $event))->toBeTrue();

    // Test the full flow by calling generatePlan + postComment
    $generatePlan = new ReflectionMethod($command, 'generatePlan');
    $plan = $generatePlan->invoke($command, $event['payload']['issue']);

    expect($plan)->toBe('## Plan\nImplement dark mode.');

    $github = app(\App\Services\GitHubService::class);
    $github->postComment('jordanpartridge/triage-agent', 42, "## 🤖 Triage Agent\n\n{$plan}\n\n---\n*Generated by triage-agent via deepseek-coder:6.7b*");

    Http::assertSent(function ($request) {
        return str_contains($request->url(), '/issues/42/comments')
            && str_contains($request['body'], 'Triage Agent');
    });
});

it('skips non-issue events', function () {
    $command = app(TriageListenCommand::class);
    $method = new ReflectionMethod($command, 'shouldProcess');

    $event = json_decode(makeEvent(['eventType' => 'pull_request']), true);

    expect($method->invoke($command, $event))->toBeFalse();
});

it('skips non-opened actions', function () {
    $command = app(TriageListenCommand::class);
    $method = new ReflectionMethod($command, 'shouldProcess');

    $event = json_decode(makeEvent(['payload' => ['action' => 'closed']]), true);

    expect($method->invoke($command, $event))->toBeFalse();
});

it('skips null events', function () {
    $command = app(TriageListenCommand::class);
    $method = new ReflectionMethod($command, 'shouldProcess');

    expect($method->invoke($command, null))->toBeFalse();
});
