<?php

namespace App\Commands;

use App\Services\GitHubService;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Process;
use Illuminate\Support\Facades\Redis;
use LaravelZero\Framework\Commands\Command;
use Prism\Prism\Enums\Provider;
use Prism\Prism\Facades\Prism;

class TriageListenCommand extends Command
{
    protected $signature = 'triage:listen';

    protected $description = 'Listen for new GitHub issues via Redis pub/sub and post AI triage plans';

    public function handle(GitHubService $github): void
    {
        $this->info('Subscribing to bifrost.github channel...');

        Redis::subscribe(['bifrost.github'], function (string $message) use ($github) {
            $envelope = json_decode($message, true);

            if (! $envelope) {
                return;
            }

            // Unwrap Laravel broadcast envelope: {"event":"...","data":{...},"socket":null}
            $event = $envelope['data'] ?? $envelope;

            $handler = $this->resolveHandler($event);

            if ($handler === null) {
                return;
            }

            $handler($event, $github);
        });
    }

    protected function resolveHandler(array $event): ?\Closure
    {
        $eventType = $event['eventType'] ?? null;
        $action = $event['payload']['action'] ?? null;

        $handlers = [
            'issues.opened' => fn (array $e, GitHubService $g) => $this->handleIssueOpened($e, $g),
            'issues.labeled' => fn (array $e, GitHubService $g) => $this->handleIssueLabeled($e, $g),
            'pull_request.opened' => fn (array $e, GitHubService $g) => $this->handlePullRequestOpened($e, $g),
            'pull_request.closed' => fn (array $e, GitHubService $g) => $this->handlePullRequestClosed($e),
        ];

        $key = "{$eventType}.{$action}";

        return $handlers[$key] ?? null;
    }

    protected function handleIssueOpened(array $event, GitHubService $github): void
    {
        $payload = $event['payload'];
        $repo = $payload['repository']['full_name'];
        $issue = $payload['issue'];
        $defaultBranch = $payload['repository']['default_branch'] ?? 'main';

        $this->info("Triaging issue #{$issue['number']}: {$issue['title']}");

        $tree = $github->getRepoTree($repo, $defaultBranch);
        $plan = $this->generatePlan($issue, $tree, $repo);

        $comment = "## Triage Agent\n\n{$plan}\n\n---\n*Generated by triage-agent via ".config('services.triage.model').'*';

        $github->postComment($repo, $issue['number'], $comment);

        $this->info("Posted triage comment on {$repo}#{$issue['number']}");
    }

    protected function handleIssueLabeled(array $event, GitHubService $github): void
    {
        $payload = $event['payload'];
        $label = $payload['label']['name'] ?? '';
        $repo = $payload['repository']['full_name'];
        $issue = $payload['issue'];

        $agentLabel = config('services.agentctl.label', 'agent-ready');
        $allowedRepos = config('services.agentctl.allowed_repos', []);

        if ($label !== $agentLabel) {
            return;
        }

        if (! empty($allowedRepos) && ! in_array($repo, $allowedRepos)) {
            $this->warn("Repo {$repo} not in allowed list for agent spawning");

            return;
        }

        $this->info("Agent-ready label detected on {$repo}#{$issue['number']}: {$issue['title']}");

        $repoUrl = $payload['repository']['ssh_url'] ?? "git@github.com:{$repo}.git";
        $agentName = 'issue-'.($issue['number'] ?? 'unknown');

        $task = "You are working on GitHub issue #{$issue['number']} for {$repo}. "
            ."Issue title: {$issue['title']}\n\n"
            ."Issue body:\n{$issue['body']}\n\n"
            .'Create a feature branch, implement the changes, write tests, run the test suite and code style fixer, '
            ."then commit, push, and create a PR referencing issue #{$issue['number']}.";

        $spawn = Process::run(['agentctl', 'spawn', $agentName, $repoUrl]);

        if (! $spawn->successful()) {
            $this->error("Failed to spawn agent: {$spawn->errorOutput()}");
            Log::error("agentctl spawn failed for {$repo}#{$issue['number']}: {$spawn->errorOutput()}");

            return;
        }

        $this->info("Spawned agent: {$agentName}");

        Process::start(['agentctl', 'run', $agentName, $task]);

        $this->info("Agent {$agentName} running on {$repo}#{$issue['number']}");
    }

    protected function handlePullRequestOpened(array $event, GitHubService $github): void
    {
        $payload = $event['payload'];
        $repo = $payload['repository']['full_name'];
        $pr = $payload['pull_request'];

        $this->info("Reviewing PR #{$pr['number']}: {$pr['title']}");

        $summary = $this->generatePrSummary($pr, $repo);

        $comment = "## Triage Agent (PR Review)\n\n{$summary}\n\n---\n*Generated by triage-agent via ".config('services.triage.model').'*';

        $github->postComment($repo, $pr['number'], $comment);

        $this->info("Posted PR review on {$repo}#{$pr['number']}");
    }

    protected function handlePullRequestClosed(array $event): void
    {
        $payload = $event['payload'];
        $pr = $payload['pull_request'] ?? null;

        if (! $pr || ! ($pr['merged'] ?? false)) {
            return;
        }

        $repo = $payload['repository']['full_name'] ?? 'unknown/repo';
        $number = $pr['number'] ?? 0;
        $title = $pr['title'] ?? 'Untitled PR';
        $body = $pr['body'] ?? '';
        $branch = $pr['head']['ref'] ?? 'unknown';
        $author = $pr['user']['login'] ?? 'unknown';
        $mergedAt = $pr['merged_at'] ?? now()->toIso8601String();

        $this->info("Capturing merged PR #{$number}: {$title}");

        $content = "PR #{$number} merged into {$repo}.\n\nBranch: {$branch}\nAuthor: {$author}\nMerged: {$mergedAt}";
        if ($body !== '') {
            $content .= "\n\nDescription:\n{$body}";
        }

        $result = Process::run([
            'know', 'add', "PR #{$number}: {$title}",
            '--content', $content,
            '--category', 'architecture',
            '--tags', "pr-merge,{$repo}",
            '--source', $pr['html_url'] ?? '',
            '--repo', $repo,
            '--branch', $branch,
            '--author', $author,
            '--status', 'validated',
            '--confidence', '80',
            '--no-git',
        ]);

        if ($result->successful()) {
            $this->info("Knowledge entry created for PR #{$number}");
        } else {
            $this->error("Failed to create knowledge entry: {$result->errorOutput()}");
            Log::error("know CLI failed for PR #{$number}: {$result->errorOutput()}");
        }
    }

    protected function generatePlan(array $issue, array $tree = [], string $repo = ''): string
    {
        $repoContext = $this->buildRepoContext($tree, $repo);

        $systemPrompt = <<<PROMPT
You are a principal architect producing an implementation spec for an engineering team.
Write like a technical design document — precise, opinionated, and ready to execute.
{$repoContext}
Use this format:

### Objective
One sentence. What ships when this is done.

### Architecture Decision
2-3 sentences on the approach chosen and why.

### File Changes
For each file: **`path/to/file`** (modify|new) with concrete changes.

### Test Plan
| File | Test Case | Technique |

### Implementation Order
Numbered steps. Each is one atomic action.

Rules:
- Reference ONLY files from the repo tree
- Name exact methods and classes
- No platitudes — be specific and actionable
PROMPT;

        $userMessage = "Issue: {$issue['title']}\n\n{$issue['body']}";

        $response = Prism::text()
            ->using(Provider::OpenRouter, config('services.triage.model'))
            ->withSystemPrompt($systemPrompt)
            ->withPrompt($userMessage)
            ->withClientOptions(['timeout' => 120])
            ->asText();

        return $response->text;
    }

    protected function generatePrSummary(array $pr, string $repo): string
    {
        $systemPrompt = <<<'PROMPT'
You are a senior software engineer reviewing a pull request.
Provide a concise review covering:
- What the PR does
- Key changes to look for during review
- Any potential concerns
Keep it actionable.
PROMPT;

        $body = $pr['body'] ?? '(no description)';
        $userMessage = "PR: {$pr['title']}\n\nDescription:\n{$body}\n\nChanged files: ".($pr['changed_files'] ?? 'unknown');

        $response = Prism::text()
            ->using(Provider::OpenRouter, config('services.triage.model'))
            ->withSystemPrompt($systemPrompt)
            ->withPrompt($userMessage)
            ->withClientOptions(['timeout' => 120])
            ->asText();

        return $response->text;
    }

    protected function buildRepoContext(array $tree, string $repo): string
    {
        if (empty($tree)) {
            return '';
        }

        $fileList = implode("\n", array_map(fn (string $path) => "- {$path}", $tree));

        return <<<CONTEXT

Repository: {$repo}
Project structure:
{$fileList}

CONTEXT;
    }
}
