<?php

namespace App\Commands;

use App\Services\GitHubService;
use Illuminate\Support\Facades\Redis;
use LaravelZero\Framework\Commands\Command;
use Prism\Prism\Enums\Provider;
use Prism\Prism\Facades\Prism;

class TriageListenCommand extends Command
{
    protected $signature = 'triage:listen';

    protected $description = 'Listen for new GitHub issues via Redis pub/sub and post AI triage plans';

    public function handle(GitHubService $github): void
    {
        $this->info('Subscribing to bifrost.github channel...');

        Redis::subscribe(['bifrost.github'], function (string $message) use ($github) {
            $event = json_decode($message, true);

            if (! $this->shouldProcess($event)) {
                return;
            }

            $payload = $event['payload'];
            $repo = $payload['repository']['full_name'];
            $issue = $payload['issue'];

            $this->info("Triaging issue #{$issue['number']}: {$issue['title']}");

            $plan = $this->generatePlan($issue);

            $comment = "## 🤖 Triage Agent\n\n{$plan}\n\n---\n*Generated by triage-agent via ".config('services.ollama.model').'*';

            $github->postComment($repo, $issue['number'], $comment);

            $this->info("Posted triage comment on {$repo}#{$issue['number']}");
        });
    }

    protected function shouldProcess(?array $event): bool
    {
        if (! $event) {
            return false;
        }

        if (($event['eventType'] ?? null) !== 'issues') {
            return false;
        }

        if (($event['payload']['action'] ?? null) !== 'opened') {
            return false;
        }

        return true;
    }

    protected function generatePlan(array $issue): string
    {
        $systemPrompt = <<<'PROMPT'
You are a senior software engineer triaging a new GitHub issue.
Analyze the issue and provide a concise implementation plan.

Respond with a markdown implementation plan including:
- Summary of what needs to be done
- Suggested approach (2-4 steps)
- Key files or areas likely affected
- Potential risks or considerations

Keep it actionable and concise.
PROMPT;

        $userMessage = "Issue: {$issue['title']}\n\n{$issue['body']}";

        $response = Prism::text()
            ->using(Provider::Ollama, config('services.ollama.model'))
            ->withSystemPrompt($systemPrompt)
            ->withPrompt($userMessage)
            ->asText();

        return $response->text;
    }
}
